routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Chapter\ChapterController;
use App\Http\Controllers\Explanation\ShowExplanationController;
use App\Http\Controllers\Home\DashboardController;
use App\Http\Controllers\Legal\LegalController;
use App\Http\Controllers\Page\PageController;
use App\Http\Controllers\Search\SearchController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/imprint', function () {
    return view('presentation.index');
})->name('index');

Route::get('/', function () {
    return view('presentation.index');
})->name('index');

Route::get('/home', DashboardController::class)->name('dashboard');

Route::get('/chapter', ChapterController::class)->name('chapter');

Route::get('/explanation', ShowExplanationController::class)->name('explanation');

Route::get('/logout', LogoutController::class)->name('logout');

Route::get('/page/{page}', PageController::class)->name('page.show');

Route::get('/search', SearchController::class)->name('search');

Route::get('/imprint', [LegalController::class, 'imprint'])->name('imprint');
Route::get('/data-protection', [LegalController::class, 'dataprotection'])->name('dataprotection');
Route::get('/terms', [LegalController::class, 'terms'])->name('terms');

app/Models/Chapter.php
<?php

namespace App\Models;

use App\Services\Transkribus\TranskribusService;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Chapter extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'next_chapter_id', 'is_absolute', 'has_strophes', 'previous_chapter_id'];

    protected $appends = ['link'];

    public function next_chapter() {
        return $this->belongsTo( Chapter::class, 'next_chapter_id', 'id');
    }

    public function previous_chapter() {
        return $this->belongsTo( Chapter::class, 'previous_chapter_id', 'id');
    }

    public function search_strings() {
        return $this->hasMany( SearchString::class, 'chapter_id', 'id');
    }

    public function next_chapters() {
        return $this->hasMany( Chapter::class, 'previous_chapter_id', 'id');
    }

    public function previous_chapters() {
        return $this->hasMany( Chapter::class, 'next_chapter_id', 'id');
    }

    public function pages() {
        return $this->hasMany( Page::class, 'chapter_id', 'id');
    }

    public function getTeaserImageLinkAttribute() {
        $service = app()->get(TranskribusService::class);

        $firstPage = $this->pages()->orderBy('page_number')->first();

        $fileName = $service->getFileNameFromFileNumber($firstPage->page_number, 'jpg');

        return safeMix('/assets/pages/' . $fileName);
    }

    public function getFirstThreeLinesAttribute() {
        $firstPage = $this->pages()->orderBy('page_number')->first();
        $firstTextArea = $firstPage->text_areas()->whereHas('lines', function($q) {
            $q->whereNotNull('value')->where('value', '<>', '');
        })->orderBy('reading_number')->first();

        return $firstTextArea->lines()->whereNotNull('value')->where('value', '<>', '')->take(3)->get();
    }

    public function getFirstPageAttribute() {
        $firstPage = $this->pages()->orderBy('page_number')->first();

        return $firstPage;
    }

    public function getLinkAttribute() {
        $firstPage = $this->first_page;

        return $firstPage->link;
    }
}

app/Http/Controllers/Chapter/ChapterController.php
<?php

namespace App\Http\Controllers\Chapter;

use App\Http\Controllers\Controller;
use App\Models\Chapter;
use Illuminate\Http\Request;

class ChapterController extends Controller
{
    public function __invoke()
    {
        $chapters = Chapter::with('pages')->get();

        return view('chapter.index')->with('chapters', $chapters);
    }
}

resources/views/chapter/index.blade.php
<x-layouts.app-layout>
    <x-slot name="content">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <x-essentials.card>
                        <x-slot name="header">
                            Ambraser Heldenbuch
                        </x-slot>

                        <x-slot name="body">
                            <div class="row">
                                <div class="col-12">
                                    <h1>Forschungsprojekt</h1>
                                    <p>Das ÖAW-go!digital-2.0-Projekt <a href="https://www.uibk.ac.at/projects/ahb/" target="_blank" rel="noopener noreferrer">»Ambraser Heldenbuch: Transkription und wissenschaftliches Datenset«</a> setzte sich zum Ziel, bis zum Jahr 2019&nbsp;– dem 500.&nbsp;Todestag von Maximilian&nbsp;I.&nbsp;– das ›Ambraser Heldenbuch‹ (Wien, Österreichische Nationalbibliothek, Cod. ser. nova 2663) aus dem frühen 16.&nbsp;Jahrhundert zur Gänze zu transkribieren. Das ›Ambraser Heldenbuch‹ wurde am Beginn des 16.&nbsp;Jahrhunderts von Maximilian&nbsp;I. als Prunkhandschrift in Auftrag gegeben und vom Bozner Zöllner Hans Ried in einer Hand auf knapp 250&nbsp;großformatigen Pergamentblättern ausgeführt. In diesem Prachtkodex finden sich 25 der wichtigsten mittelhochdeutschen literarischen Texte (z.&nbsp;B. ›Nibelungenlied‹ und ›Helmbrecht‹), wovon 15 als Unikate (z.&nbsp;B. ›Erec‹ und ›Mauritius von Craûn‹) ausschließlich im ›Ambraser Heldenbuch‹ überliefert sind.</p>
                                    <p>Aufgrund der großen Textmenge in einer Schreiberhand&nbsp;– das ›Ambraser Heldenbuch‹ und vier weitere bekannte Schriftzeugnisse (Urkunde, Zollregister und Dienstreversen) von Hans Ried umfassen ca.&nbsp;600.000&nbsp;Wörter&nbsp;– eignet sich eine Gesamttranskription der Ried’schen Autographe als einmaliges linguistisches und literaturwissenschaftliches Korpus:</p>
                                    <ol>
                                        <li>Aus editionsphilologischer Sicht ermöglicht das Korpus einzigartige Möglichkeiten für die mittelhochdeutsche Textrekonstruktion der als Unikate im ›Ambraser Heldenbuch‹ überlieferten Werke, aber auch für die Edition und Erforschung der Parallelüberlieferungen (z.&nbsp;B. ›Nibelungenlied‹).</li>
                                        <li>Aus linguistischer und dialektologischer Sicht erschließt die Transkription des ›Ambraser Heldenbuchs‹ zusammen mit den anderen Schriftstücken von Hans Ried ein geographisch liminales Großkorpus am Übergang von Mittelalter zu Früher Neuzeit aus einer Schreiberhand.</li>
                                    </ol>
                                    <p class="mb-0">Unter historischen Linguist*innen und Editionsphilolog*innen gilt die Gesamttranskription des ›Ambraser Heldenbuchs‹ und der Ried’schen Autographe seit vielen Jahren als vorrangiges Forschungsdesiderat. Ziel des Projekts war daher eine auf dem Stand der Technik durchgeführte elaborierte Transkription des Gesamttexts des ›Ambraser Heldenbuchs‹ sowie die Aufbereitung dieser Transkription als öffentlich zugängliches und zitierbares Datenset, das als künftiges Referenzdokument für eine breite Palette an wissenschaftlichen Arbeiten dienen soll.</p>
                                </div>
                            </div>

                            <hr class="my-4" />

                            <div class="row">
                                <h3>Text wählen</h3>

                                @foreach($chapters as $chapter)
                                    <a href="{{ route('page.show', ['page' => $chapter->first_page->id]) }}" class="col-12 col-md-6 col-lg-4 col-xl-3 my-3">
                                        <x-essentials.card class="h-100" img-link="{{ $chapter->teaser_image_link }}">
                                            <x-slot name="body">
                                                <h5>
                                                    {{ $chapter->name }}
                                                </h5>

                                                @foreach($chapter->first_three_lines as $line)
                                                    <div class="junicode">
                                                        {{ $line->value }}
                                                    </div>
                                                @endforeach
                                            </x-slot>
                                        </x-essentials.card>
                                    </a>
                                @endforeach
                            </div>
                        </x-slot>
                    </x-essentials.card>
                </div>
            </div>
        </div>
    </x-slot>
</x-layouts.app-layout>